language: php

services:
  - mongodb
 
cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
        - ENABLE_EXT_MONGO=true
    - php: 5.6
      env:
        - DEPS=latest
        - ENABLE_EXT_MONGO=true
    - php: 7
      env:
        - DEPS=lowest
        - ENABLE_EXT_MONGODB=true
    - php: 7
      env:
        - DEPS=latest
        - CS_CHECK=true
        - TEST_COVERAGE=true
        - ENABLE_EXT_MONGODB=true
    - php: 7.1
      env:
        - DEPS=lowest
        - ENABLE_EXT_MONGODB=true
    - php: 7.1
      env:
        - DEPS=latest
        - ENABLE_EXT_MONGODB=true
    - php: 7.2
      env:
        - DEPS=lowest
        - ENABLE_EXT_MONGODB=true
    - php: 7.2
      env:
        - DEPS=latest
        - ENABLE_EXT_MONGODB=true
    - php: 7.3
      env:
        - DEPS=latest
        - ENABLE_EXT_MONGODB=true
    - php: 7.4
      env:
        - DEPS=latest
        - ENABLE_EXT_MONGODB=true
  
before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - if [[ $ENABLE_EXT_MONGO == 'true' ]]; then echo "Enabling mongo extension"; echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; fi
  - if [[ $ENABLE_EXT_MONGODB == 'true' ]]; then echo "Enabling mongodb extension"; echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; fi

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $LEGACY_DEPS != '' ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - if [[ $ENABLE_EXT_MONGODB == 'true' ]]; then composer require --dev $COMPOSER_ARGS alcaeus/mongo-php-adapter ; fi
  - stty cols 120 && composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi

notifications:
  email: false
